### ISSUE TITLE
Integrate with NestedSampling-hs

### ISSUE THREAD

**Issue by eggplantbren** [jtobin/deanie#1]
Can we have deanie create the required functions for use with NestedSampling-hs? That would be great.

**Comment by jtobin** [comment]
I didn't realize this issue was still open. 😅  But I think this is impossible to do cleanly -- reifying a posterior from a model description seems to be pretty tricky, and might require dependent types.

**Comment by eggplantbren** [comment]
To be honest I don't really understand why, because it's basically what BUGS and Stan already do. Happy to trust your judgment, though.

**Comment by jtobin** [comment]
You can do it for simple finite models (i.e. the kind that BUGS or Stan support) but it winds up being pretty hacky.  Basically you have to add extra annotations for every variable in the model, along the lines of:

```
foo = do
  a <- bar (Tag "a")
  b <- baz a (Tag "b")
  c <- qux b (Tag "c")
  zop c (Tag "x")
```

The core problem is that since *deanie* is a language *embedded* in Haskell, you can't actually observe bound variable names (the `a`, `b`, `c`, etc. in `a <- ...`) in an interpreter, and so need to rely on something else to keep track of them when doing inference, reporting results, etc.  BUGS and Stan are standalone thingies (i.e. they aren't embedded in some other host language), so they don't have the same issue.

There are probably other ways to do this, via Template Haskell (hacky; probably not a total solution anyway) or something like the `bound` library maybe, but I've never tried them.

If one is willing to live with the additional fugly tagging syntax, It is indeed pretty easy to write something that reifies a posterior for basic (i.e. non-recursive, non-dynamic in size) models.  Maybe it would be worth implementing that in a separate library?  `posterior-reifier`? 😄

**Comment by eggplantbren** [comment]
Gotcha. I have actually come across this myself in the past: https://plausibilitytheory.wordpress.com/2016/08/11/a-jags-like-interface-to-dnest4/
